services:
  - type: web
    name: serikbay
    plan: free
    env: docker
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: API_ID
        sync: false
      - key: API_HASH
        sync: false
      - key: PYTHON_VERSION
        value: 3.10.0