services:
  - type: web
    name: serikbay
    env: python
    buildCommand: pip install -r backend/requirements.txt
    startCommand: uvicorn backend.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: DATA_DIR
        value: /data
      - key: API_ID
        sync: false
      - key: API_HASH
        sync: false
      - key: PYTHON_VERSION
        value: 3.10.0
    disk:
      name: serikbay-data
      mountPath: /data
      sizeGB: 1
